services:
  exchange-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "15173:3000"
    env_file:
      - ./frontend/.env.exchange
    stdin_open: true
    tty: true
    restart: unless-stopped
