-- Oracle 19c Database Seed Data
-- Purpose: DML only (no CREATE TABLE/INDEX/TRIGGER)

MERGE INTO FEE_TIERS T
USING (
    SELECT 1 AS TIER_LEVEL, 'Bronze' AS TIER_NAME, 0 AS MIN_VOLUME, 1000000 AS MAX_VOLUME, 0.0020 AS FEE_RATE FROM DUAL
    UNION ALL
    SELECT 2, 'Silver', 1000001, 10000000, 0.0015 FROM DUAL
    UNION ALL
    SELECT 3, 'Gold', 10000001, NULL, 0.0010 FROM DUAL
) S
ON (T.TIER_LEVEL = S.TIER_LEVEL)
WHEN NOT MATCHED THEN
    INSERT (TIER_LEVEL, TIER_NAME, MIN_VOLUME, MAX_VOLUME, FEE_RATE)
    VALUES (S.TIER_LEVEL, S.TIER_NAME, S.MIN_VOLUME, S.MAX_VOLUME, S.FEE_RATE);

MERGE INTO MEMBERS M
USING (SELECT 'admin@vce.com' AS EMAIL FROM DUAL) S
ON (M.EMAIL = S.EMAIL)
WHEN NOT MATCHED THEN
    INSERT (EMAIL, PASSWORD, NAME, ROLE, STATUS, RRN_PREFIX, PHONE_NUMBER)
    VALUES (
        'admin@vce.com',
        '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07NWqE2G.n7XN7S4Gi',
        '관리자',
        'ADMIN',
        'ACTIVE',
        '0000000',
        '010-0000-0000'
    );

COMMIT;
