-- Oracle 19c Database Schema
-- Project: Security-Focused Crypto Exchange (Vulnerability Lab)
-- Date: 2026-02-14
-- ========================================================

-- 1. Member Information (회원정보)
-- ========================================================
CREATE TABLE MEMBERS (
    MEMBER_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL           VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD        VARCHAR2(255) NOT NULL,
    NAME            VARCHAR2(50) NOT NULL,
    RRN_PREFIX      VARCHAR2(20),  -- 7에서 20으로 확장
    PHONE_NUMBER    VARCHAR2(20),  -- NULL 허용으로 변경
    ADDRESS         VARCHAR2(200),
    ACCOUNT_NUMBER  VARCHAR2(50),           
    ID_PHOTO_URL    VARCHAR2(255),          
    ROLE            VARCHAR2(20) DEFAULT 'USER' CHECK (ROLE IN ('USER', 'ADMIN', 'GUEST')), -- GUEST 추가
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'LOCKED', 'WITHDRAWN', 'PENDING')), -- PENDING 추가
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE MEMBERS IS '회원 정보 테이블';

-- 2. Fee Tiers (수수료 티어)
-- ========================================================
CREATE TABLE FEE_TIERS (
    TIER_LEVEL      NUMBER PRIMARY KEY,      
    TIER_NAME       VARCHAR2(50),            
    MIN_VOLUME      NUMBER(19, 4) DEFAULT 0, 
    MAX_VOLUME      NUMBER(19, 4),           
    FEE_RATE        NUMBER(5, 4) NOT NULL    
);

-- 3. Assets & Orders (자산 및 주문)
-- ========================================================
CREATE TABLE ASSETS (
    ASSET_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER NOT NULL,
    ASSET_TYPE      VARCHAR2(20) NOT NULL,   -- 'KRW', 'BTC' 등
    BALANCE         NUMBER(19, 8) DEFAULT 0, -- 가용 자산
    LOCKED_BALANCE  NUMBER(19, 8) DEFAULT 0, -- 주문 등으로 묶인 자산
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ASSETS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_MEMBER_ASSET UNIQUE (MEMBER_ID, ASSET_TYPE)
);

CREATE TABLE ORDERS (
    ORDER_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER NOT NULL,
    ORDER_TYPE      VARCHAR2(10) NOT NULL CHECK (ORDER_TYPE IN ('BUY', 'SELL')),
    ASSET_TYPE      VARCHAR2(20) NOT NULL,
    PRICE           NUMBER(19, 8) NOT NULL,
    AMOUNT          NUMBER(19, 8) NOT NULL,
    FILLED_AMOUNT   NUMBER(19, 8) DEFAULT 0,
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'PARTIAL', 'FILLED', 'CANCELLED')),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);
COMMENT ON TABLE ORDERS IS '미체결 내역 및 주문 관리 테이블';

CREATE TABLE TRANSACTIONS (
    TX_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER NOT NULL,
    ORDER_ID        NUMBER, -- 실시간 거래인 경우 ORDER_ID 참조
    TX_TYPE         VARCHAR2(20) NOT NULL CHECK (TX_TYPE IN ('BUY', 'SELL', 'DEPOSIT', 'WITHDRAW', 'FEE')),
    ASSET_TYPE      VARCHAR2(20) NOT NULL,
    AMOUNT          NUMBER(19, 8) NOT NULL,
    PRICE           NUMBER(19, 8),           
    TOTAL_VALUE     NUMBER(19, 8),           
    FEE             NUMBER(19, 8) DEFAULT 0, 
    TX_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TX_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TX_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- 4. Community Board (커뮤니티 및 첨부파일)
-- ========================================================
CREATE TABLE POSTS (
    POST_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER NOT NULL,
    TITLE           VARCHAR2(200) NOT NULL,
    CONTENT         CLOB NOT NULL,
    ATTACHMENT_URL  VARCHAR2(500), -- 사진 업로드 대응
    IS_NOTICE       CHAR(1) DEFAULT 'N' CHECK (IS_NOTICE IN ('Y', 'N')),
    IS_HIDDEN       CHAR(1) DEFAULT 'N' CHECK (IS_HIDDEN IN ('Y', 'N')),
    VIEW_COUNT      NUMBER DEFAULT 0,
    LIKE_COUNT      NUMBER DEFAULT 0,        
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_POSTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE SET NULL
);

CREATE TABLE COMMENTS (
    COMMENT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POST_ID         NUMBER NOT NULL,
    MEMBER_ID       NUMBER NOT NULL,
    CONTENT         VARCHAR2(1000) NOT NULL,
    IS_HIDDEN       CHAR(1) DEFAULT 'N' CHECK (IS_HIDDEN IN ('Y', 'N')),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMENTS_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE
);

CREATE TABLE LIKES (
    LIKE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TARGET_TYPE     VARCHAR2(10) NOT NULL CHECK (TARGET_TYPE IN ('POST', 'COMMENT')),
    TARGET_ID       NUMBER NOT NULL,
    MEMBER_ID       NUMBER NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LIKES_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_LIKES_TARGET UNIQUE (MEMBER_ID, TARGET_TYPE, TARGET_ID)
);

-- 5. Security Audit Log (보안 감사 로그)
-- ========================================================
CREATE TABLE AUDIT_LOGS (
    LOG_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER,
    ACTION          VARCHAR2(100) NOT NULL, -- e.g., 'LOGIN_SUCCESS', 'PASSWORD_CHANGE', 'ADMIN_ACCESS'
    IP_ADDRESS      VARCHAR2(50),
    USER_AGENT      VARCHAR2(255),
    TARGET_TABLE    VARCHAR2(50),
    TARGET_ID       NUMBER,
    LOG_DETAIL      CLOB,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE AUDIT_LOGS IS '보안 진단 및 사고 분석용 로그 테이블';

-- 6. Indexes
-- ========================================================
CREATE INDEX IDX_MEMBERS_EMAIL ON MEMBERS(EMAIL);
CREATE INDEX IDX_POSTS_NOTICE ON POSTS(IS_NOTICE DESC, CREATED_AT DESC);
CREATE INDEX IDX_TRANSACTIONS_MEMBER ON TRANSACTIONS(MEMBER_ID, TX_DATE DESC);
CREATE INDEX IDX_ORDERS_MEMBER ON ORDERS(MEMBER_ID, STATUS);
CREATE INDEX IDX_AUDIT_ACTION ON AUDIT_LOGS(ACTION, CREATED_AT DESC);

-- 7. Triggers (Automatic UPDATED_AT)
-- ========================================================
CREATE OR REPLACE TRIGGER TRG_MEMBERS_UPDATE
BEFORE UPDATE ON MEMBERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
-- 8. Initial Data
-- ========================================================
-- Fee Tiers
INSERT INTO FEE_TIERS (TIER_LEVEL, TIER_NAME, MIN_VOLUME, MAX_VOLUME, FEE_RATE) VALUES (1, 'BRONZE', 0, 1000000, 0.0008);
INSERT INTO FEE_TIERS (TIER_LEVEL, TIER_NAME, MIN_VOLUME, MAX_VOLUME, FEE_RATE) VALUES (2, 'SILVER', 1000001, 10000000, 0.0005);
INSERT INTO FEE_TIERS (TIER_LEVEL, TIER_NAME, MIN_VOLUME, MAX_VOLUME, FEE_RATE) VALUES (3, 'GOLD', 10000001, 100000000, 0.0003);
INSERT INTO FEE_TIERS (TIER_LEVEL, TIER_NAME, MIN_VOLUME, MAX_VOLUME, FEE_RATE) VALUES (4, 'VIP', 100000001, NULL, 0.0001);

-- Test Admin Account (password: admin123)
INSERT INTO MEMBERS (EMAIL, PASSWORD, NAME, ROLE, STATUS, RRN_PREFIX, PHONE_NUMBER) 
VALUES ('admin@vce.com', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07NWqE2G.n7XN7S4Gi', '관리자', 'ADMIN', 'ACTIVE', '000000-0', '010-0000-0000');

COMMIT;
CREATE OR REPLACE TRIGGER TRG_POSTS_UPDATE
BEFORE UPDATE ON POSTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/