-- Oracle Database Schema
-- Project: Security-Focused Crypto Exchange (Vulnerability Lab)
-- Purpose: DDL only (tables, indexes, triggers)

CREATE TABLE FEE_TIERS (
    TIER_LEVEL      NUMBER PRIMARY KEY,
    TIER_NAME       VARCHAR2(50) NOT NULL,
    MIN_VOLUME      NUMBER(19, 4) DEFAULT 0,
    MAX_VOLUME      NUMBER(19, 4),
    FEE_RATE        NUMBER(5, 4) NOT NULL
);

CREATE TABLE MEMBERS (
    MEMBER_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL               VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD            VARCHAR2(255),
    NAME                VARCHAR2(50) NOT NULL,
    RRN_PREFIX          VARCHAR2(20),
    PHONE_NUMBER        VARCHAR2(20),
    ADDRESS             VARCHAR2(200),
    BANK_NAME           VARCHAR2(30),
    ACCOUNT_NUMBER      VARCHAR2(50),
    ACCOUNT_HOLDER      VARCHAR2(50),
    ID_PHOTO_URL        VARCHAR2(255),
    REFERRAL_CODE       VARCHAR2(20) UNIQUE,
    REFERRED_BY_CODE    VARCHAR2(20),
    ROLE                VARCHAR2(20) DEFAULT 'GUEST'   CHECK (ROLE   IN ('USER', 'VCESYS_CORE', 'VCESYS_MGMT', 'VCESYS_EMP', 'GUEST')),
    STATUS              VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('ACTIVE', 'LOCKED', 'WITHDRAWN', 'PENDING', 'AUTH_FAILED')),
    LOGIN_FAIL_COUNT    NUMBER DEFAULT 0 NOT NULL,
    TIER_LEVEL          NUMBER DEFAULT 1,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MEMBERS_TIER FOREIGN KEY (TIER_LEVEL) REFERENCES FEE_TIERS(TIER_LEVEL)
);

-- 관리자 전용 계정 테이블 (일반 회원 MEMBERS와 분리)
CREATE TABLE ADMIN_MEMBERS (
    ADMIN_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL               VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD            VARCHAR2(255) NOT NULL,
    NAME                VARCHAR2(50) NOT NULL,
    ROLE                VARCHAR2(20) DEFAULT 'VCESYS_EMP' CHECK (ROLE IN ('VCESYS_CORE', 'VCESYS_MGMT', 'VCESYS_EMP')),
    STATUS              VARCHAR2(20) DEFAULT 'ACTIVE'     CHECK (STATUS IN ('ACTIVE', 'LOCKED', 'WITHDRAWN', 'AUTH_FAILED')),
    LOGIN_FAIL_COUNT    NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ASSETS (
    ASSET_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER NOT NULL,
    ASSET_TYPE      VARCHAR2(20) NOT NULL,
    BALANCE         NUMBER(19, 8) DEFAULT 0,
    LOCKED_BALANCE  NUMBER(19, 8) DEFAULT 0,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ASSETS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_MEMBER_ASSET UNIQUE (MEMBER_ID, ASSET_TYPE)
);

CREATE TABLE ORDERS (
    ORDER_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER NOT NULL,
    ORDER_TYPE      VARCHAR2(10) NOT NULL CHECK (ORDER_TYPE IN ('BUY', 'SELL')),
    PRICE_TYPE      VARCHAR2(10) DEFAULT 'LIMIT' CHECK (PRICE_TYPE IN ('LIMIT', 'MARKET')),
    ASSET_TYPE      VARCHAR2(20) NOT NULL,
    PRICE           NUMBER(19, 8),
    AMOUNT          NUMBER(19, 8) NOT NULL,
    FILLED_AMOUNT   NUMBER(19, 8) DEFAULT 0,
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'PARTIAL', 'FILLED', 'CANCELLED')),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

CREATE TABLE TRANSACTIONS (
    TX_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER NOT NULL,
    ORDER_ID        NUMBER,
    TX_TYPE         VARCHAR2(20) NOT NULL CHECK (TX_TYPE IN ('BUY', 'SELL', 'DEPOSIT', 'WITHDRAW', 'FEE')),
    ASSET_TYPE      VARCHAR2(20) NOT NULL,
    AMOUNT          NUMBER(19, 8) NOT NULL,
    PRICE           NUMBER(19, 8),
    TOTAL_VALUE     NUMBER(19, 8),
    FEE             NUMBER(19, 8) DEFAULT 0,
    TX_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TX_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TX_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE POSTS (
    POST_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER,
    TITLE           VARCHAR2(200) NOT NULL,
    CONTENT         CLOB NOT NULL,
    ATTACHMENT_URL  VARCHAR2(500),
    IS_NOTICE       CHAR(1) DEFAULT 'N' CHECK (IS_NOTICE IN ('Y', 'N')),
    IS_HIDDEN       CHAR(1) DEFAULT 'N' CHECK (IS_HIDDEN IN ('Y', 'N')),
    VIEW_COUNT      NUMBER DEFAULT 0,
    LIKE_COUNT      NUMBER DEFAULT 0,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_POSTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE SET NULL
);

CREATE TABLE COMMENTS (
    COMMENT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POST_ID         NUMBER NOT NULL,
    MEMBER_ID       NUMBER,
    CONTENT         VARCHAR2(1000) NOT NULL,
    IS_HIDDEN       CHAR(1) DEFAULT 'N' CHECK (IS_HIDDEN IN ('Y', 'N')),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMENTS_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE SET NULL
);

CREATE TABLE LIKES (
    LIKE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TARGET_TYPE     VARCHAR2(10) NOT NULL CHECK (TARGET_TYPE IN ('POST', 'COMMENT')),
    TARGET_ID       NUMBER NOT NULL,
    MEMBER_ID       NUMBER NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LIKES_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_LIKES_TARGET UNIQUE (MEMBER_ID, TARGET_TYPE, TARGET_ID)
);

CREATE TABLE AUDIT_LOGS (
    LOG_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID       NUMBER,
    ACTION          VARCHAR2(100) NOT NULL,
    IP_ADDRESS      VARCHAR2(50),
    USER_AGENT      VARCHAR2(255),
    TARGET_TABLE    VARCHAR2(50),
    TARGET_ID       NUMBER,
    LOG_DETAIL      CLOB,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_MEMBERS_EMAIL     ON MEMBERS(EMAIL);
CREATE INDEX IDX_ADMIN_EMAIL       ON ADMIN_MEMBERS(EMAIL);
CREATE INDEX IDX_POSTS_NOTICE      ON POSTS(IS_NOTICE DESC, CREATED_AT DESC);
CREATE INDEX IDX_TRANSACTIONS_MEMBER ON TRANSACTIONS(MEMBER_ID, TX_DATE DESC);
CREATE INDEX IDX_ORDERS_MEMBER     ON ORDERS(MEMBER_ID, STATUS);
CREATE INDEX IDX_AUDIT_ACTION      ON AUDIT_LOGS(ACTION, CREATED_AT DESC);

CREATE OR REPLACE TRIGGER TRG_UPDATE_MEMBER_TIER
AFTER INSERT ON TRANSACTIONS
FOR EACH ROW
DECLARE
    V_TOTAL_VOL NUMBER;
    V_NEW_TIER  NUMBER;
BEGIN
    SELECT NVL(SUM(TOTAL_VALUE), 0) INTO V_TOTAL_VOL
    FROM TRANSACTIONS
    WHERE MEMBER_ID = :NEW.MEMBER_ID
      AND TX_TYPE IN ('BUY', 'SELL');

    SELECT TIER_LEVEL INTO V_NEW_TIER
    FROM FEE_TIERS
    WHERE V_TOTAL_VOL >= MIN_VOLUME
      AND (V_TOTAL_VOL <= MAX_VOLUME OR MAX_VOLUME IS NULL)
    FETCH FIRST 1 ROW ONLY;

    UPDATE MEMBERS
    SET TIER_LEVEL = V_NEW_TIER
    WHERE MEMBER_ID = :NEW.MEMBER_ID;
END;
/

CREATE OR REPLACE TRIGGER TRG_MEMBERS_UPDATE
BEFORE UPDATE ON MEMBERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ADMIN_MEMBERS_UPDATE
BEFORE UPDATE ON ADMIN_MEMBERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_POSTS_UPDATE
BEFORE UPDATE ON POSTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
