-- Oracle Database Schema (Idempotent)
-- Project: Security-Focused Crypto Exchange (Vulnerability Lab)
-- 신규 DB, 기존 DB 구분 없이 동일하게 실행 가능합니다.
-- 에러 코드: -955(테이블 존재), -1430(컬럼 존재), -2264(제약 존재), -1408(인덱스 존재)

-- ── FEE_TIERS ────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE FEE_TIERS (
            TIER_LEVEL  NUMBER PRIMARY KEY,
            TIER_NAME   VARCHAR2(50)  NOT NULL,
            MIN_VOLUME  NUMBER(19, 4) DEFAULT 0,
            MAX_VOLUME  NUMBER(19, 4),
            FEE_RATE    NUMBER(5, 4)  NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── MEMBERS ──────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE MEMBERS (
            MEMBER_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            EMAIL            VARCHAR2(100) NOT NULL UNIQUE,
            PASSWORD         VARCHAR2(255),
            NAME             VARCHAR2(50)  NOT NULL,
            RRN_PREFIX       VARCHAR2(20),
            PHONE_NUMBER     VARCHAR2(20),
            ADDRESS          VARCHAR2(200),
            BANK_NAME        VARCHAR2(30),
            ACCOUNT_NUMBER   VARCHAR2(50),
            ACCOUNT_HOLDER   VARCHAR2(50),
            ID_PHOTO_URL     VARCHAR2(255),
            REFERRAL_CODE    VARCHAR2(20) UNIQUE,
            REFERRED_BY_CODE VARCHAR2(20),
            ROLE             VARCHAR2(20) DEFAULT ''GUEST''
                             CHECK (ROLE IN (''USER'', ''VCESYS_CORE'', ''VCESYS_MGMT'', ''VCESYS_EMP'', ''GUEST'')),
            STATUS           VARCHAR2(20) DEFAULT ''PENDING''
                             CHECK (STATUS IN (''ACTIVE'', ''LOCKED'', ''WITHDRAWN'', ''PENDING'', ''AUTH_FAILED'')),
            LOGIN_FAIL_COUNT NUMBER       DEFAULT 0 NOT NULL,
            BANK_BALANCE     NUMBER(19,8) DEFAULT 50000000 NOT NULL,
            TIER_LEVEL       NUMBER       DEFAULT 1,
            CREATED_AT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_MEMBERS_TIER FOREIGN KEY (TIER_LEVEL) REFERENCES FEE_TIERS(TIER_LEVEL)
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 참고: 관리자 계정은 MEMBERS 테이블에 VCESYS_* ROLE로 저장됨 (ADMIN_MEMBERS 미사용)
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ADMIN_MEMBERS (
            ADMIN_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            EMAIL            VARCHAR2(100) NOT NULL UNIQUE,
            PASSWORD         VARCHAR2(255) NOT NULL,
            NAME             VARCHAR2(50)  NOT NULL,
            ROLE             VARCHAR2(20) DEFAULT ''VCESYS_EMP''
                             CHECK (ROLE IN (''VCESYS_CORE'', ''VCESYS_MGMT'', ''VCESYS_EMP'')),
            STATUS           VARCHAR2(20) DEFAULT ''ACTIVE''
                             CHECK (STATUS IN (''ACTIVE'', ''LOCKED'', ''WITHDRAWN'', ''AUTH_FAILED'')),
            LOGIN_FAIL_COUNT NUMBER    DEFAULT 0 NOT NULL,
            CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── ASSETS ───────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ASSETS (
            ASSET_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            MEMBER_ID         NUMBER NOT NULL,
            ASSET_TYPE        VARCHAR2(20) NOT NULL,
            BALANCE           NUMBER(19,8) DEFAULT 0,
            LOCKED_BALANCE    NUMBER(19,8) DEFAULT 0,
            AVERAGE_BUY_PRICE NUMBER(19,8) DEFAULT 0,
            UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_ASSETS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
            CONSTRAINT UQ_MEMBER_ASSET  UNIQUE (MEMBER_ID, ASSET_TYPE)
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 기존 DB: AVERAGE_BUY_PRICE 컬럼이 없는 경우 추가
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ASSETS ADD AVERAGE_BUY_PRICE NUMBER(19,8) DEFAULT 0';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- ── ORDERS ───────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ORDERS (
            ORDER_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            MEMBER_ID     NUMBER NOT NULL,
            ORDER_TYPE    VARCHAR2(10) NOT NULL CHECK (ORDER_TYPE IN (''BUY'', ''SELL'')),
            PRICE_TYPE    VARCHAR2(10) DEFAULT ''LIMIT'' CHECK (PRICE_TYPE IN (''LIMIT'', ''MARKET'')),
            ASSET_TYPE    VARCHAR2(20) NOT NULL,
            PRICE         NUMBER(19,8),
            AMOUNT        NUMBER(19,8) NOT NULL,
            FILLED_AMOUNT NUMBER(19,8) DEFAULT 0,
            STATUS        VARCHAR2(20) DEFAULT ''PENDING''
                          CHECK (STATUS IN (''PENDING'', ''PARTIAL'', ''FILLED'', ''CANCELLED'')),
            CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── TRANSACTIONS ─────────────────────────────────────────────────────────────
-- TX_TYPE: BUY/SELL(주문), DEPOSIT/WITHDRAW(입출금), FEE(수수료),
--          ADMIN_RECLAIM(관리자회수), ATTENDANCE_REWARD(출석보상), AD_MISSION_REWARD(광고미션보상)
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE TRANSACTIONS (
            TX_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            MEMBER_ID      NUMBER NOT NULL,
            ORDER_ID       NUMBER,
            TX_TYPE        VARCHAR2(20) NOT NULL
                           CHECK (TX_TYPE IN (
                               ''BUY'', ''SELL'', ''DEPOSIT'', ''WITHDRAW'', ''FEE'',
                               ''ADMIN_RECLAIM'', ''ATTENDANCE_REWARD'', ''AD_MISSION_REWARD''
                           )),
            ASSET_TYPE     VARCHAR2(20) NOT NULL,
            AMOUNT         NUMBER(19,8) NOT NULL,
            PRICE          NUMBER(19,8),
            TOTAL_VALUE    NUMBER(19,8),
            FEE            NUMBER(19,8) DEFAULT 0,
            TX_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FROM_ADDRESS   VARCHAR2(255),
            TO_ADDRESS     VARCHAR2(255),
            TX_HASH        VARCHAR2(255),
            BANK_NAME      VARCHAR2(50),
            ACCOUNT_NUMBER VARCHAR2(100),
            STATUS         VARCHAR2(20) DEFAULT ''COMPLETED'',
            CONSTRAINT FK_TX_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
            CONSTRAINT FK_TX_ORDER  FOREIGN KEY (ORDER_ID)  REFERENCES ORDERS(ORDER_ID)
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 기존 DB: 누락 컬럼 추가
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRANSACTIONS ADD FROM_ADDRESS   VARCHAR2(255)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRANSACTIONS ADD TO_ADDRESS     VARCHAR2(255)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRANSACTIONS ADD TX_HASH        VARCHAR2(255)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRANSACTIONS ADD BANK_NAME      VARCHAR2(50)';  EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRANSACTIONS ADD ACCOUNT_NUMBER VARCHAR2(100)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRANSACTIONS ADD STATUS VARCHAR2(20) DEFAULT ''COMPLETED'''; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- 기존 DB: 구버전 TX_TYPE CHECK 제약 삭제 후 신규 제약으로 교체
BEGIN
    FOR c IN (
        SELECT constraint_name
        FROM   user_constraints
        WHERE  table_name       = 'TRANSACTIONS'
          AND  constraint_type  = 'C'
          AND  UPPER(search_condition) LIKE '%TX_TYPE%'
          AND  constraint_name != 'CHK_TX_TYPE'
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE TRANSACTIONS DROP CONSTRAINT ' || c.constraint_name;
    END LOOP;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE TRANSACTIONS ADD CONSTRAINT CHK_TX_TYPE CHECK (TX_TYPE IN (
            ''BUY'', ''SELL'', ''DEPOSIT'', ''WITHDRAW'', ''FEE'',
            ''ADMIN_RECLAIM'', ''ATTENDANCE_REWARD'', ''AD_MISSION_REWARD''
        ))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

-- ── WALLETS ──────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE WALLETS (
            WALLET_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            MEMBER_ID       NUMBER NOT NULL,
            ASSET_TYPE      VARCHAR2(20)  NOT NULL,
            DEPOSIT_ADDRESS VARCHAR2(255) NOT NULL UNIQUE,
            CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_WALLETS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── INQUIRIES ────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE INQUIRIES (
            INQUIRY_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            MEMBER_ID      NUMBER NOT NULL,
            TITLE          VARCHAR2(200) NOT NULL,
            CONTENT        CLOB NOT NULL,
            STATUS         VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL,
            REPLY          CLOB,
            ATTACHMENT_URL VARCHAR2(500),
            CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_INQUIRIES_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── FAQS ─────────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE FAQS (
            FAQ_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            CATEGORY VARCHAR2(100) NOT NULL,
            QUESTION VARCHAR2(500) NOT NULL,
            ANSWER   CLOB NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── REVOKED_TOKENS ───────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE REVOKED_TOKENS (
            TOKEN_ID       VARCHAR2(64) PRIMARY KEY,
            MEMBER_EMAIL   VARCHAR2(100),
            TOKEN_TYPE     VARCHAR2(20) NOT NULL,
            REVOKED_REASON VARCHAR2(100),
            EXPIRES_AT     TIMESTAMP NOT NULL,
            REVOKED_AT     TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── POSTS ────────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE POSTS (
            POST_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            MEMBER_ID      NUMBER,
            TITLE          VARCHAR2(200) NOT NULL,
            CONTENT        CLOB NOT NULL,
            ATTACHMENT_URL VARCHAR2(500),
            IS_NOTICE      CHAR(1) DEFAULT ''N'' CHECK (IS_NOTICE IN (''Y'', ''N'')),
            IS_HIDDEN      CHAR(1) DEFAULT ''N'' CHECK (IS_HIDDEN IN (''Y'', ''N'')),
            VIEW_COUNT     NUMBER DEFAULT 0,
            LIKE_COUNT     NUMBER DEFAULT 0,
            CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_POSTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE SET NULL
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── COMMENTS ─────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE COMMENTS (
            COMMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            POST_ID    NUMBER NOT NULL,
            MEMBER_ID  NUMBER,
            CONTENT    VARCHAR2(1000) NOT NULL,
            IS_HIDDEN  CHAR(1) DEFAULT ''N'' CHECK (IS_HIDDEN IN (''Y'', ''N'')),
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_COMMENTS_POST   FOREIGN KEY (POST_ID)   REFERENCES POSTS(POST_ID)     ON DELETE CASCADE,
            CONSTRAINT FK_COMMENTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE SET NULL
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── LIKES ────────────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE LIKES (
            LIKE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            TARGET_TYPE VARCHAR2(10) NOT NULL CHECK (TARGET_TYPE IN (''POST'', ''COMMENT'')),
            TARGET_ID   NUMBER NOT NULL,
            MEMBER_ID   NUMBER NOT NULL,
            CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_LIKES_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
            CONSTRAINT UQ_LIKES_TARGET UNIQUE (MEMBER_ID, TARGET_TYPE, TARGET_ID)
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── AUDIT_LOGS ───────────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE AUDIT_LOGS (
            LOG_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            MEMBER_ID    NUMBER,
            ACTION       VARCHAR2(100) NOT NULL,
            IP_ADDRESS   VARCHAR2(50),
            USER_AGENT   VARCHAR2(255),
            TARGET_TABLE VARCHAR2(50),
            TARGET_ID    NUMBER,
            LOG_DETAIL   CLOB,
            CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── 인덱스 ──────────────────────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_MEMBERS_EMAIL       ON MEMBERS(EMAIL)';                        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_ADMIN_EMAIL         ON ADMIN_MEMBERS(EMAIL)';                  EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_POSTS_NOTICE        ON POSTS(IS_NOTICE DESC, CREATED_AT DESC)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TRANSACTIONS_MEMBER ON TRANSACTIONS(MEMBER_ID, TX_DATE DESC)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_ORDERS_MEMBER       ON ORDERS(MEMBER_ID, STATUS)';             EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_AUDIT_ACTION        ON AUDIT_LOGS(ACTION, CREATED_AT DESC)';  EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_WALLETS_MEMBER      ON WALLETS(MEMBER_ID, ASSET_TYPE)';        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_REVOKED_TOKENS_EXP  ON REVOKED_TOKENS(EXPIRES_AT)';           EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1408 THEN RAISE; END IF; END;
/

-- ── 트리거 ──────────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER TRG_UPDATE_MEMBER_TIER
AFTER INSERT ON TRANSACTIONS
FOR EACH ROW
DECLARE
    V_TOTAL_VOL NUMBER;
    V_NEW_TIER  NUMBER;
BEGIN
    SELECT NVL(SUM(TOTAL_VALUE), 0) INTO V_TOTAL_VOL
    FROM TRANSACTIONS
    WHERE MEMBER_ID = :NEW.MEMBER_ID
      AND TX_TYPE IN ('BUY', 'SELL');

    SELECT TIER_LEVEL INTO V_NEW_TIER
    FROM FEE_TIERS
    WHERE V_TOTAL_VOL >= MIN_VOLUME
      AND (V_TOTAL_VOL <= MAX_VOLUME OR MAX_VOLUME IS NULL)
    FETCH FIRST 1 ROW ONLY;

    UPDATE MEMBERS
    SET TIER_LEVEL = V_NEW_TIER
    WHERE MEMBER_ID = :NEW.MEMBER_ID;
END;
/

CREATE OR REPLACE TRIGGER TRG_MEMBERS_UPDATE
BEFORE UPDATE ON MEMBERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ADMIN_MEMBERS_UPDATE
BEFORE UPDATE ON ADMIN_MEMBERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_POSTS_UPDATE
BEFORE UPDATE ON POSTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
