services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env.backend

    environment:
      - SERVER_PORT=18080
      - SERVER_FORWARD_HEADERS_STRATEGY=${SERVER_FORWARD_HEADERS_STRATEGY:-framework}
      - UPLOAD_DIR=${UPLOAD_DIR:-/app/uploads}

    ports:
      - "8080:18080"

    volumes:
      - uploads:${UPLOAD_DIR:-/app/uploads}

    restart: unless-stopped

volumes:
  uploads:
